import type { SiteAdapter } from './base';
import bbob from '@bbob/html';
import presetHTML5 from '@bbob/preset-html5';

/**
 * 1Point3Acres adapter
 * Uses internal API to fetch thread data and converts BBCode to Markdown
 */
export const onePoint3AcresAdapter: SiteAdapter = {
    name: '1Point3Acres',
    urlPatterns: [
        'https://www.1point3acres.com/bbs/thread-*',
        'https://www.1point3acres.com/home/pins/*',
        'https://instant.1point3acres.com/thread/*',
    ],
    includesFrontmatter: true,  // Templates generate complete markdown with frontmatter
    // extractMetadata disabled - frontmatter is generated by templates in fetch1Point3AcresContent
    preProcess: (element) => {
        // This adapter uses API, but this hook can still be used
        // for any DOM-based preprocessing if needed
        return element;
    },
};

/**
 * Fetch thread content from 1Point3Acres API
 * Returns Markdown content using templates from config
 */
export async function fetch1Point3AcresContent(
    threadId: string,
    onProgress?: (message: string) => void
): Promise<string | null> {
    try {
        const apiUrl = `https://api.1point3acres.com/api/v3/home-threads/${threadId}`;
        console.log(`[Markify] Fetching thread content from: ${apiUrl}`);

        // Fetch thread data
        const response = await new Promise<any>((resolve, reject) => {
            GM.xmlHttpRequest({
                method: 'GET',
                url: apiUrl,
                onload: (res) => {
                    if (res.status >= 200 && res.status < 300) {
                        try {
                            resolve(JSON.parse(res.responseText));
                        } catch (e) {
                            reject(new Error('Failed to parse JSON response'));
                        }
                    } else {
                        reject(new Error(`API request failed: ${res.status}`));
                    }
                },
                onerror: () => reject(new Error('Network error')),
            });
        });

        if (response.errno !== 0 || !response.thread) {
            throw new Error('Invalid API response');
        }

        const thread = response.thread;

        // Get templates from config
        const templates = (globalThis as any).__MARKIFY_TEMPLATES__?.['1point3acres'] || {};
        const frontmatterTemplate = templates.frontmatter?.template || '---\ntitle: "{title}"\nauthor: {author}\nposted_at: {posted_at}\nupdated_at: {updated_at}\ndownloaded_at: {downloaded_at}\nsource: {url}\nviews: {views}\nreplies: {replies}\nfavorites: {favorites}\ntags:\n  - 1point3acres\n  - forum\n---\n';
        const docTemplate = templates.document?.template || '{frontmatter}\n# {title}\n\n**Author:** {author} | **Date:** {date}\n\n---\n\n{content}\n\n---\n\n**Views:** {views} | **Replies:** {replies} | **Favorites:** {favorites}\n\n{comments}';
        const commentTemplate = templates.comment?.template || '\n**{author}** - *{date}*\n\n{content}\n\n{delimiter}\n';
        const commentsHeaderTemplate = templates.comments_header?.template || '\n\n{delimiter}\n\n## Comments ({count})\n';
        const delimiter = templates.delimiter || '---';

        // Convert BBCode content to HTML first, then let Turndown convert to Markdown
        const contentHtml = convertBBCodeToHTML(thread.message_bbcode || '');


        // Build comments section with pagination
        let commentsMarkdown = '';
        if (thread.replies > 0) {
            try {
                // Get API config from templates
                const apiConfig = templates.api || {};
                const pageSize = apiConfig.page_size || 20;
                const order = apiConfig.order || 'time_asc';
                const maxPages = apiConfig.max_pages || 50;

                let allPosts: any[] = [];
                let currentPage = 1;
                let hasMorePages = true;

                console.log(`[Markify] Fetching ${thread.replies} comments with pagination (${pageSize} per page)...`);

                // Fetch all pages
                while (hasMorePages && currentPage <= maxPages) {
                    const postsUrl = `https://api.1point3acres.com/api/threads/${threadId}/nested-posts?ps=${pageSize}&order=${order}&pg=${currentPage}`;
                    console.log(`[Markify] Fetching page ${currentPage}: ${postsUrl}`);

                    // Update progress
                    if (onProgress) {
                        onProgress(`📥 Fetching page ${currentPage}/${Math.ceil(thread.replies / pageSize)}...`);
                    }

                    const postsResponse = await new Promise<any>((resolve, reject) => {
                        GM.xmlHttpRequest({
                            method: 'GET',
                            url: postsUrl,
                            onload: (res) => {
                                if (res.status >= 200 && res.status < 300) {
                                    try {
                                        resolve(JSON.parse(res.responseText));
                                    } catch (e) {
                                        reject(new Error('Failed to parse posts JSON'));
                                    }
                                } else {
                                    reject(new Error(`Posts request failed: ${res.status}`));
                                }
                            },
                            onerror: () => reject(new Error('Network error fetching posts')),
                        });
                    });

                    if (postsResponse.posts && Array.isArray(postsResponse.posts)) {
                        allPosts = allPosts.concat(postsResponse.posts);
                        console.log(`[Markify] Page ${currentPage}: ${postsResponse.posts.length} comments (total: ${allPosts.length})`);

                        // Check if there are more pages
                        if (postsResponse.posts.length < pageSize) {
                            hasMorePages = false;
                        } else {
                            currentPage++;
                        }
                    } else {
                        hasMorePages = false;
                    }
                }

                if (allPosts.length > 0) {
                    // Add comments header with total count
                    commentsMarkdown = commentsHeaderTemplate
                        .replace(/{count}/g, allPosts.length.toString())
                        .replace(/{delimiter}/g, delimiter);

                    // Sort by time if needed (time_desc returns newest first, so reverse for oldest first)
                    if (order === 'time_desc') {
                        allPosts.reverse();
                    }

                    allPosts.forEach((post: any) => {
                        const postDate = new Date(post.dateline * 1000).toLocaleString();
                        const postContentHtml = convertBBCodeToHTML(post.message_bbcode || '');

                        // Render comment with placeholders
                        const comment = commentTemplate
                            .replace(/{author}/g, post.author)
                            .replace(/{date}/g, postDate)
                            .replace(/{content}/g, postContentHtml)
                            .replace(/{delimiter}/g, delimiter);

                        commentsMarkdown += comment;
                    });

                    console.log(`[Markify] Successfully added ${allPosts.length} comments from ${currentPage - 1} pages`);
                }
            } catch (error) {
                console.error('[Markify] Error fetching posts:', error);
                // Continue without posts if fetch fails
            }
        }

        // Build frontmatter
        const threadUrl = `https://www.1point3acres.com/bbs/thread-${threadId}-1-1.html`;
        const postDate = new Date(thread.dateline * 1000).toISOString();
        const lastUpdated = new Date(thread.lastpost * 1000).toISOString();
        const downloadedDate = new Date().toISOString();
        const sourceLink = `"[${thread.subject}](${threadUrl})"`;  // Format as Markdown link

        const frontmatter = frontmatterTemplate
            .replace(/{title}/g, thread.subject)
            .replace(/{author}/g, thread.author)
            .replace(/{posted_at}/g, postDate)
            .replace(/{updated_at}/g, lastUpdated)
            .replace(/{downloaded_at}/g, downloadedDate)
            .replace(/{url}/g, sourceLink)
            .replace(/{views}/g, thread.views.toString())
            .replace(/{replies}/g, thread.replies.toString())
            .replace(/{favorites}/g, (thread.favtimes || 0).toString());

        // Build final document using template
        const markdown = docTemplate
            .replace(/{frontmatter}/g, frontmatter)
            .replace(/{title}/g, thread.subject)
            .replace(/{author}/g, thread.author)
            .replace(/{date}/g, new Date(thread.dateline * 1000).toLocaleString())
            .replace(/{content}/g, contentHtml)
            .replace(/{views}/g, thread.views.toString())
            .replace(/{replies}/g, thread.replies.toString())
            .replace(/{favorites}/g, (thread.favtimes || 0).toString())
            .replace(/{comments}/g, commentsMarkdown)
            .replace(/{delimiter}/g, delimiter);

        return markdown;
    } catch (error) {
        console.error('[Markify] Error fetching 1Point3Acres content:', error);
        return null;
    }
}

/**
 * Convert BBCode to HTML using @bbob library
 */
function convertBBCodeToHTML(bbcode: string): string {
    return bbob(bbcode, presetHTML5());
}
